# Generated by Django 5.0.4 on 2024-05-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='Varsayılan Resim', upload_to='courses/%Y/%m/%d'),
        ),
    ]
