# Generated by Django 5.0.4 on 2024-05-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='selam.jpg', upload_to='courses/%Y/%m/%d'),
        ),
    ]
